### ISSUE TITLE
undefined reference to `disableAppNap()'

### ISSUE THREAD

**Issue by rountree** [julianmi/effort-log#1]
`g++ -m64 -Wl,-O1 -o build/release/effort-log build/release/.obj/activity.o build/release/.obj/appenddialog.o build/release/.obj/main.o build/release/.obj/mainwindow.o build/release/.obj/milestone.o build/release/.obj/milestonedialog.o build/release/.obj/project.o build/release/.obj/setupdialog.o build/release/.obj/proinitdialog.o build/release/.obj/questionnairedialog.o build/release/.obj/qrc_doc.o build/release/.obj/qrc_img.o build/release/.obj/moc_appenddialog.o build/release/.obj/moc_mainwindow.o build/release/.obj/moc_milestonedialog.o build/release/.obj/moc_setupdialog.o build/release/.obj/moc_proinitdialog.o build/release/.obj/moc_questionnairedialog.o   -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
build/release/.obj/mainwindow.o: In function`MainWindow::MainWindow()':
mainwindow.cc:(.text+0x1f7f): undefined reference to `disableAppNap()'
build/release/.obj/mainwindow.o: In function`MainWindow::MainWindow(Crypt_)':
mainwindow.cc:(.text+0x2012): undefined reference to `disableAppNap()'
collect2: error: ld returned 1 exit status
Makefile:188: recipe for target 'build/release/effort-log' failed
make: *_\* [build/release/effort-log] Error 1
`

System is standard ubuntu.  Here's the header for the makefile:

Makefile for building: build/release/effort-log
Generated by qmake (3.0) (Qt 5.4.2)
Project:  EffortLog.pro
Template: app
Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake PREFIX=/home/rountree/local/install -o Makefile EffortLog.pro

Working off of this commit:
commit 72d02c0511f0783f8e576a5a0ac8e750d90bb6ea
Author: julianmi julianmi@users.noreply.github.com
Date:   Thu Feb 18 17:31:07 2016 +0100

g++ version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010

**Comment by julianmi** [comment]
The problem is with a function specific to Mac OS X which should not be linked to on other platforms. I have added the missing guard. Please try again.

**Comment by rountree** [comment]
Verified fixed.  Thanks!
