### ISSUE TITLE
Comments are not getting saved into json file.

### ISSUE THREAD

**Issue by rountree** [julianmi/effort-log#2]
Next issue:  I ran the program and set up an interval of two minutes.  I created a specific directory to store the log files.  When I got through all of the dialog boxes, this was on my console:

rountree@lacunae:~/local/src/effort-log/build/release$ ./effort-log 
3
3
3
3
Couldn't open log file.

The timer expired correctly.  I was able to add a comment.

In my log directory I don't see the comment in the json file.  Here's what I have there.
ls -
rountree@lacunae:~/local/effort-log-test$ ls -l
total 12
-rw-rw-r-- 1 rountree rountree 314 Feb 23 08:14 blr-test.pro
rountree@lacunae:~/local/effort-log-test$ cat blr-test.pro 
{
    "Contributors": [
        {
            "name": "rountree"
        }
    ],
    "LogFile": "blr-test.json",
    "LogFileDirectory": "/home/rountree/local/src/effort-log/build/release",
    "LoggingInterval": 3,
    "ProjectDirectory": "/home/rountree/local/effort-log-test",
    "ProjectTitle": "blr-test"
}
rountree@lacunae:~/local/effort-log-test$

**Comment by julianmi** [comment]
Thank you very much for your feedback. 62e00bd should add the missing JSON output. Please verify the fix.
